Repository Wolfteam/Shiori, pull requests merged in 2021-07, with the labels that each got.

#90 Feature/minor_improvements
  assets/db/characters.json
  assets/db/weapons.json
  lib/application/artifacts/artifacts_bloc.dart
  lib/application/artifacts/artifacts_event.dart
  lib/application/calculator_asc_materials/calculator_asc_materials_bloc.dart
  lib/application/calculator_asc_materials/calculator_asc_materials_event.dart
  lib/application/calculator_asc_materials_sessions/calculator_asc_materials_sessions_bloc.dart
  lib/application/calculator_asc_materials_sessions/calculator_asc_materials_sessions_event.dart
  lib/application/characters/characters_bloc.dart
  lib/application/characters/characters_event.dart
  lib/application/characters/characters_state.dart
  lib/application/inventory/inventory_bloc.dart
  lib/application/inventory/inventory_event.dart
  lib/application/materials/materials_bloc.dart
  lib/application/materials/materials_event.dart
  lib/application/monsters/monsters_bloc.dart
  lib/application/monsters/monsters_event.dart
  lib/application/url_page/url_page_bloc.dart
  lib/application/weapons/weapons_bloc.dart
  lib/application/weapons/weapons_event.dart
  lib/domain/enums/item_location_type.dart
  lib/domain/models/characters/character_card_model.dart
  lib/domain/models/settings/app_settings.dart
  lib/domain/services/data_service.dart
  lib/domain/services/telemetry_service.dart
  lib/infrastructure/data_service.dart
  lib/infrastructure/genshin_service.dart
  lib/infrastructure/telemetry/telemetry_service.dart
  lib/l10n/intl_en.arb
  lib/l10n/intl_es_ES.arb
  lib/l10n/intl_id.arb
  lib/l10n/intl_it_IT.arb
  lib/l10n/intl_ja.arb
  lib/l10n/intl_pt.arb
  lib/l10n/intl_ru.arb
  lib/l10n/intl_vi.arb
  lib/l10n/intl_zh_CN.arb
  lib/presentation/artifacts/widgets/artifact_bottom_sheet.dart
  lib/presentation/calculator_asc_materials/calculator_ascension_materials_page.dart
  lib/presentation/calculator_asc_materials/calculator_sessions_page.dart
  lib/presentation/calculator_asc_materials/widgets/reoder_sessions_dialog.dart
  lib/presentation/calculator_asc_materials/widgets/reorder_items_dialog.dart
  lib/presentation/characters/widgets/character_bottom_sheet.dart
  lib/presentation/inventory/inventory_page.dart
  lib/presentation/inventory/widgets/clear_all_dialog.dart
  lib/presentation/materials/widgets/material_bottom_sheet.dart
  lib/presentation/monsters/widgets/monster_bottom_sheet.dart
  lib/presentation/shared/confirm_dialog.dart
  lib/presentation/shared/extensions/i18n_extensions.dart
  lib/presentation/shared/extensions/media_query_extensions.dart
  lib/presentation/shared/info_dialog.dart
  lib/presentation/shared/item_popupmenu_filter.dart
  lib/presentation/shared/styles.dart
  lib/presentation/shared/utils/enum_utils.dart
  lib/presentation/weapons/widgets/weapon_bottom_sheet.dart
Labels: t/feature-request, t/improvements

#93 Updated japanese translations
  assets/i18n/ja.json
  lib/l10n/intl_ja.arb
Labels: t/translations

#98 feature/desktop_support
  assets/i18n/ru.json
  lib/application/url_page/url_page_bloc.dart
  lib/infrastructure/device_info_service.dart
  lib/infrastructure/notification_service.dart
  lib/infrastructure/telemetry/flutter_appcenter_bundle.dart
  lib/main.dart
  lib/presentation/daily_check_in/daily_check_in_page.dart
  lib/presentation/main_tab_page.dart
  lib/presentation/material/widgets/material_detail_top.dart
  lib/presentation/shared/app_webview.dart
  lib/presentation/shared/styles.dart
  lib/presentation/shared/utils/size_utils.dart
  lib/presentation/weapon/widgets/weapon_detail_top.dart
  pubspec.lock
  pubspec.yaml
  windows/.gitignore
  windows/CMakeLists.txt
  windows/flutter/CMakeLists.txt
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugin_registrant.h
  windows/flutter/generated_plugins.cmake
  windows/runner/CMakeLists.txt
  windows/runner/Runner.rc
  windows/runner/flutter_window.cpp
  windows/runner/flutter_window.h
  windows/runner/main.cpp
  windows/runner/resource.h
  windows/runner/resources/app_icon.ico
  windows/runner/run_loop.cpp
  windows/runner/run_loop.h
  windows/runner/runner.exe.manifest
  windows/runner/utils.cpp
  windows/runner/utils.h
  windows/runner/win32_window.cpp
  windows/runner/win32_window.h
Labels: t/improvements

#82 Feature/french translations
  assets/i18n/fr.json
Labels: t/translations
